# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Madalin/OneDrive/SSC/VGA-Project/VGA-Project.srcs/sources_1/ip/BRAM_img1/BRAM_img1.xci
# IP: The module: 'BRAM_img1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Madalin/OneDrive/SSC/VGA-Project/VGA-Project.gen/sources_1/ip/BRAM_img1/BRAM_img1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_img1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Madalin/OneDrive/SSC/VGA-Project/VGA-Project.srcs/sources_1/ip/BRAM_img1/BRAM_img1.xci
# IP: The module: 'BRAM_img1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Madalin/OneDrive/SSC/VGA-Project/VGA-Project.gen/sources_1/ip/BRAM_img1/BRAM_img1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_img1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
